"""
Create a distributable zip for the PyInstaller onedir build.

Run after PyInstaller:
    python scripts/build_release_zip.py

The zip contains the whole FTSM-RAG folder, including _internal. This avoids the
common mistake of sending only FTSM-RAG.exe, which cannot run by itself.
"""

from __future__ import annotations

import argparse
import shutil
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_APP_DIR = ROOT / "dist" / "FTSM-RAG"
DEFAULT_OUTPUT = ROOT / "dist" / "FTSM-RAG-windows.zip"

REQUIRED_RELATIVE_PATHS = (
    "FTSM-RAG.exe",
    "_internal",
    "_internal/python312.dll",
    "_internal/web",
    "_internal/config",
    "_internal/prompts",
)

EXCLUDED_PARTS = {
    "logs",
    "__pycache__",
}


def validate_app_dir(app_dir: Path) -> list[str]:
    missing: list[str] = []
    for rel in REQUIRED_RELATIVE_PATHS:
        if not (app_dir / rel).exists():
            missing.append(rel)
    return missing


def should_include(path: Path, app_dir: Path) -> bool:
    rel_parts = path.relative_to(app_dir).parts
    return not any(part in EXCLUDED_PARTS for part in rel_parts)


def write_distribution_note(app_dir: Path) -> Path:
    note = app_dir / "README_DISTRIBUTION.txt"
    note.write_text(
        "FTSM-RAG Windows package\n"
        "========================\n\n"
        "Do not move FTSM-RAG.exe out of this folder.\n"
        "The _internal folder must stay next to FTSM-RAG.exe because it contains "
        "the embedded Python runtime and application resources.\n\n"
        "To share this app, send the zip file generated by scripts/build_release_zip.py "
        "or zip this whole FTSM-RAG folder.\n",
        encoding="utf-8",
    )
    return note


def build_zip(app_dir: Path, output: Path) -> None:
    if output.exists():
        output.unlink()
    output.parent.mkdir(parents=True, exist_ok=True)

    root_name = app_dir.name
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
        for path in app_dir.rglob("*"):
            if not path.is_file() or not should_include(path, app_dir):
                continue
            arcname = Path(root_name) / path.relative_to(app_dir)
            zf.write(path, arcname.as_posix())


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a distributable FTSM-RAG zip.")
    parser.add_argument("--app-dir", type=Path, default=DEFAULT_APP_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    app_dir = args.app_dir.resolve()
    output = args.output.resolve()

    if not app_dir.exists():
        print(f"Build folder not found: {app_dir}", file=sys.stderr)
        print("Run PyInstaller first: python -m PyInstaller --clean --noconfirm ftsm_rag.spec", file=sys.stderr)
        return 1

    missing = validate_app_dir(app_dir)
    if missing:
        print("Cannot build release zip. Missing required packaged files:", file=sys.stderr)
        for item in missing:
            print(f"  - {item}", file=sys.stderr)
        return 1

    write_distribution_note(app_dir)
    build_zip(app_dir, output)

    size_mb = output.stat().st_size / (1024 * 1024)
    print(f"Wrote {output}")
    print(f"Size: {size_mb:.1f} MB")
    print("Send this zip file, not only FTSM-RAG.exe.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

